
## Site settings
title: اسناد میرا
description: اسناد راهنمای استفاده از میرا

author: kiavash
email: kiavash@gmail.com

url: http://miraxy.github.io/doc-fa
root: /doc-fa

language: Farsi
icon: /static/img/mira.png

## default post permanent link
permalink: :chapter/:title/

## Build settings
default_markup: html

## number of posts will be show in main index page
post_num: all
post_sort: reverse
## number of posts will be show in archives index page
archive_post_num: all

template: mido

lists:
  - season

namespace:
 1: میرا
 2: استفاده
 3: محتوا
 4: پوسته
 5: قالب

