
## Site settings
title: documents
description: Mira Documents

author: kiavash
email: kiavash@gmail.com

url: http://miraxy.github.io/doc
root: /doc/

## default post permanent link
permalink: :title/

## Build settings
default_markup: mmd

## number of posts will be show in main index page
post_num: all
post_sort: reverse
## number of posts will be show in archives index page
archive_post_num: all

template: newsprint

lists:

namespace:

