
## Site settings
title: راهنمای میرا
description: اسناد راهنما برای شروع کار با میرا

author: kiavash
email: kiavash@gmail.com

url: http://miraxy.github.io/guide-fa
root: /guide-fa/

style: style-rtl.css

## default post permanent link
permalink: :title/

## Build settings
default_markup: markdown

## number of posts will be show in main index page
post_num: all
post_sort: reverse
## number of posts will be show in archives index page
archive_post_num: all

template: mira-doc

lists:
  - categories
  - chapter

namespace:
 01: start
 02: config
 03: content
 04: template
 05: parser
 06: plugin

