
#general 'mira' config, you can make config files for any floor in /config/FLOOR_NAME.yml


## Site settings
title: شروع
description: راهنمای شروع به کار با میرا

author: kiavash
email: kiavash@gmail.com

 # the base hostname & protocol for your site
url: http://miraxy.github.io/start-fa
root: /start-fa/

## default post permanent link
permalink: :title/

plugins:
 - jalali

## Your local Time Zone
TimeZone: +03:30

## Build settings
default_markup: markdown

## number of posts will be show in main index page
post_num: all
post_sort: reverse
## number of posts will be show in archives index page
archive_post_num: all

template: mira-doc

lists:
  - categories
  - chapter

namespace:
  گیت: git

